# Generated by Django 5.0.6 on 2024-07-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='offerings',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
