# Generated by Django 5.0.2 on 2024-07-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_exact_location_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='offerings',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
