services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports: 
      - '5173:5173'
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '8000:8000'
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379' 