# Generated by Django 5.0.6 on 2024-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authour_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='authour_name',
            field=models.CharField(default='DEFAULT NAME', max_length=30),
        ),
    ]
