# Generated by Django 5.0.6 on 2024-06-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authour_id',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='authour_name',
            new_name='author_name',
        ),
    ]
