# Generated by Django 5.0.6 on 2024-06-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
