# Generated by Django 5.0.6 on 2024-06-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.CharField(default=2.1, max_length=10),
            preserve_default=False,
        ),
    ]
