# Generated by Django 5.0.6 on 2024-06-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_latitude_alter_post_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.CharField(max_length=30),
        ),
    ]
