# Generated by Django 5.0.6 on 2024-07-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_authour_id_post_authour_name'),
        ('posts', '0010_remove_post_latitude_remove_post_longitude'),
    ]

    operations = [
    ]
