# Generated by Django 5.0.2 on 2024-07-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_merge_20240705_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='authour_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='authour_name',
        ),
    ]
