# Generated by Django 5.0.6 on 2024-07-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_merge_20240705_2252'),
        ('posts', '0011_merge_20240706_2141'),
    ]

    operations = [
    ]
